# app/config/routing.yml
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

xaben_forum:
    resource: "@XabenForumBundle/Resources/config/routing.yml"
    prefix:   /forum
    
dtmedia_profile:
    resource: "@XabenProfileBundle/Resources/config/routing.yml"